-- QUESTAO 2

-- a)
UPDATE FEDERACAO SET
    NOME_FD = 'Nova Aliança Galática',
    DATA_FUND = TO_DATE('22/03/3200','dd/mm/yyyy')
WHERE NOME_FD = 'Aliança Galáctica';


--INSERT INTO FEDERACAO (NOME_FD, DATA_FUND) VALUES ('Aliança Galáctica', TO_DATE('01/01/2200','dd/mm/yyyy'));
--INSERT INTO FEDERACAO (NOME_FD, DATA_FUND) VALUES ('Comando Estelar', TO_DATE('09-10-2199', 'DD-MM-YYYY'));

--SELECT * FROM FEDERACAO;
--DELETE FROM FEDERACAO;



--b)
UPDATE ESPECIE SET
    EH_INTELIGENTE = 'N'
WHERE PLANETA_ORIGEM = 'Terra';


--c)
UPDATE PLANETA SET
    CLASSIFICACAO = NULL;

