-- 3.A)
SELECT F.NOME_FC AS NOME_FACCAO, F.IDEOLOGIA AS IDEOLODIA_FACCAO, L.NOME AS LIDER, L.ESPECIE AS ESPECIE_LIDER, L.NACAO AS NACAO_LIDER
FROM FACCAO F JOIN LIDER L
ON F.LIDER_FC = L.CPI;

 
-- 3.B)
-- inserindo um lider que nao eh responsavel por nenhuma faccao, para testar o left join
INSERT INTO LIDER (CPI, NOME, CARGO, NACAO, ESPECIE) VALUES (3, 'Anakin Skywalker', 'Comandante', 'Terra Unida', 'Humanos');

SELECT L.CPI, L.NOME, L.NACAO, L.ESPECIE, E.PLANETA_ORIGEM, F.NOME_FC
FROM LIDER L
JOIN ESPECIE E ON L.ESPECIE = E.NOME_CIENTIFICO
LEFT JOIN FACCAO F ON L.CPI = F.LIDER_FC;

-- 3.C)
-- insercao de mais estrelas e relacao orbitaestrela para teste
INSERT INTO ESTRELA (ID_CATALOGO, NOME, CLASSIFICACAO, MASSA, COORDENADA_X, COORDENADA_Y, COORDENADA_Z) VALUES ('78910', 'Sirius', 'Classe A', 2.0 * POWER(10, 30), 100, 200, 300);
INSERT INTO ESTRELA (ID_CATALOGO, NOME, CLASSIFICACAO, MASSA, COORDENADA_X, COORDENADA_Y, COORDENADA_Z) VALUES ('10987', 'Aldebaran', 'Classe B', 1.5 * POWER(10, 30), 150, 250, 350);
INSERT INTO ESTRELA (ID_CATALOGO, NOME, CLASSIFICACAO, MASSA, COORDENADA_X, COORDENADA_Y, COORDENADA_Z) VALUES ('11121', 'Vega', 'Classe F', 1.8 * POWER(10, 30), 200, 300, 400);

INSERT INTO ORBITAESTRELA (ORBITANTE, ORBITADA, DISTANCIA_MIN, DISTANCIA_MAX, PERIODO) VALUES ('78910', '10987', 75, 125, 400);
INSERT INTO ORBITAESTRELA (ORBITANTE, ORBITADA, DISTANCIA_MIN, DISTANCIA_MAX, PERIODO) VALUES ('11121', '10987', 150, 200, 500);

SELECT E1.NOME AS NOME_ORBITANTE, E1.CLASSIFICACAO AS CLASSIFICACAO_ORBITANTE,
E2.NOME AS NOME_ORBITADA, E2.CLASSIFICACAO AS CLASSIFICACAO_ORBITADA
FROM ORBITAESTRELA OE
JOIN ESTRELA E1 ON OE.ORBITANTE = E1.ID_CATALOGO
JOIN ESTRELA E2 ON OE.ORBITADA = E2.ID_CATALOGO;

-- 3.E)
-- insercao de algumas comunidades e habitacoes para testar o count
INSERT INTO COMUNIDADE (ESPECIE, NOME, QTD_HABITANTES) VALUES ('Humanos', 'Nova Terra', 10000000);
INSERT INTO COMUNIDADE (ESPECIE, NOME, QTD_HABITANTES) VALUES ('Humanos', 'Torradinhos', 5000000);
INSERT INTO COMUNIDADE (ESPECIE, NOME, QTD_HABITANTES) VALUES ('Humanos', 'Terra 2.0', 5000000);

INSERT INTO HABITACAO (PLANETA, COM_ESPECIE, COM_NOME, DT_INICIO, DT_FIM) VALUES ('Marte', 'Humanos', 'Nova Terra', TO_DATE('2216-03-20', 'YYYY-MM-DD'), NULL);
INSERT INTO HABITACAO (PLANETA, COM_ESPECIE, COM_NOME, DT_INICIO, DT_FIM) VALUES ('Venus', 'Humanos', 'Torradinhos', TO_DATE('2200-01-01', 'YYYY-MM-DD'), TO_DATE('2200-01-02', 'YYYY-MM-DD'));
INSERT INTO HABITACAO (PLANETA, COM_ESPECIE, COM_NOME, DT_INICIO, DT_FIM) VALUES ('Marte', 'Humanos', 'Terra 2.0', TO_DATE('2310-01-01', 'YYYY-MM-DD'), NULL);

SELECT H.PLANETA, H.COM_ESPECIE AS ESPECIE,
COUNT(*) AS QTD_COMUNIDADES
FROM HABITACAO H
GROUP BY H.PLANETA, H.COM_ESPECIE;
